package com.hospitaltender.server.enums;

public enum ReportType {
    LUZUM_MUZEKKERESI,
    TEKLIF_MEKTUBU,
    IHTIYAC_TESPIT_KARARI,
    GOREVLENDIRME,
    YAKLASIK_MALIYET_CETVELI,
    PIYASA_ARASTIRMA_TUTANAGI,
    KOMISYON_KARARI,
    IHALE_ONAY_BELGESI,
    MUAYENE_KABUL_TUTANAGI
}
